config/routes.rb
Rails.application.routes.draw do
  RailsApiTester::Application.routes.draw do
  resources :users
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 require 'rest_client'

  USERNAME = "myfinance@gmail.com" # needed to access the APi
  PASSWORD = "credit123" # needed to access the APi
  #API_BASE_URL = "http://localhost:3000/api" # base url of the API
  API_BASE_URL = "http://nameless-everglades-1789.herokuapp.com//api" # base url of the API

  def index
    uri = "#{API_BASE_URL}/users.json" # specifying json format in the URl
    rest_resource = RestClient::Resource.new(uri, USERNAME, PASSWORD) # It will create
    # new rest-client resource so that we can call different methods of it
    users = rest_resource.get # will get back you all the detail in json format, but it
    #will we wraped as string, so we will parse it in the next step.
    @users = JSON.parse(users, :symbolize_names => true) # we will convert the return
    #data into array of hash.see json data parsing here
  end

  def new

  end

  #NOTE :  see below how we are passing the payload and content type while making the post call
  def create
    uri = "#{API_BASE_URL}/users"
    payload = params.to_json # converting the params to json
    rest_resource = RestClient::Resource.new(uri, USERNAME, PASSWORD)
    begin
      rest_resource.post payload , :content_type => "application/json"
      flash[:notice] = "User Saved successfully"
      redirect_to users_path # take back to index page, which now list the newly created user also
    rescue Exception => e
     flash[:error] = "User Failed to save"
     render :new
    end
  end

  def edit
    # uri = "#{API_BASE_URL}/users/#{params[:id]}.json" # specifying format as json so that
    #                                                   #json data is returned
    # rest_resource = RestClient::Resource.new(uri, USERNAME, PASSWORD)
    # users = rest_resource.get
    # @user = JSON.parse(users, :symbolize_names => true)
  end

  def update
    # uri = "#{API_BASE_URL}/users/#{params[:id]}"
    # payload = params.to_json
    # rest_resource = RestClient::Resource.new(uri, USERNAME, PASSWORD)
    # begin
    #   rest_resource.put payload , :content_type => "application/json"
    #   flash[:notice] = "User Updated successfully"
    # rescue Exception => e
    #   flash[:error] = "User Failed to Update"
    # end
    # redirect_to users_path
  end

  def destroy
    # uri = "#{API_BASE_URL}/users/#{params[:id]}"
    # rest_resource = RestClient::Resource.new(uri, USERNAME, PASSWORD)
    # begin
    #  rest_resource.delete
    #  flash[:notice] = "User Deleted successfully"
    # rescue Exception => e
    #  flash[:error] = "User Failed to Delete"
    # end
    # redirect_to users_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsApiTester</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<%= link_to "Create New User", new_user_path %>
<%if @users.present? %>
  <p>Below is the list of users</p>
  <table width="100%">
    <tr>
      <td>ID</td>
      <td>name</td>
      <td>email</td>
      <td>Action</td>
    </tr>
    NOTE : the @users object in our index action is array of hash, which is generated
    when be passed return data to JSON.parse method. If you handled data in some other
    way, modify the code below accordingly. say for xml data you have to use something like
    u.xpath("id").text instead of u[:id]
    <%@users.each do |u|%>
    <tr>
      <td><%=u[:id]%></td>
      <td><%=u[:name]%></td>
      <td><%=u[:email]%></td>
      <td>
        <%= link_to "Edit", edit_user_path(u[:id]) %> |
        <%= link_to "Delete", user_path(u[:id]), :method => :delete %>
      </td>
    </tr>
   <%end%>
  </table>
<%else%>
  <p>No User is Found</p>
<%end%>